pre_bump_hooks = [
  "echo {{version}}",
]

# post_bump_hooks = [
#     "git push",
#     "git push origin {{version}}",
# ]

[changelog]
authors = [
  {username = "heeckhau", signature = "Hendrik Eeckhaut"},
]
owner = "TLSNotary"
path = "CHANGELOG.md"
remote = "github.com"
repository = "https://github.com/tlsnotary/proof_viz"
template = "remote"
